server:
  port: 8080

spring:
  application:
    name: hackathon-ai-2023-yateam
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: '*'
