server:
  port: 8080

spring:
  application:
    name: hackathon-ai-2023-yateam
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:hackathon-ai-2023-yateam
    username: h2user
    password: h2pass

management:
  endpoints:
    web:
      exposure:
        include: info, health
