name: Build and Push Docker image

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Build React with Npm
        working-directory: src/main/webapp
        run: |
          npm install
          npm run build

      - name: Move files to resources
        run: |
          mkdir -p src/main/resources/static
          cp -r src/main/webapp/build/* src/main/resources/static/

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build JAR with Gradle
        run: ./gradlew assemble

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            airndlab/hackathon-ai-2023-yateam:${{ github.ref_name }}
            airndlab/hackathon-ai-2023-yateam:latest
          build-args: |
            JAR_FILE=build/libs/*.jar
            CONFIG_FILE=config/application-docker.yml
