name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle 'assemble'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Login to Google Cloud Registry
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: _json_key
          password: ${{ secrets.YC_JSON_KEY }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: cr.yandex/crpg8n96fsaji4i8glgo/yateam/hackathon-ai-2023-yateam:1
          build-args: |
            JAR_FILE=build/libs/*.jar
            CONFIG_FILE=config/application-docker.yml
